name: Deploy Model

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS}}

      - name: Log in to Azure Container Registry
        run: az acr login --name ${{secrets.ACR_USERNAME}}

      - name: Set MODEL_URI environment variable
        run: echo "MODEL_URI=models:/${{ vars.MODEL_NAME }}@${{ secrets.MODEL_ALIAS }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -f ./deployment/Dockerfile -t ${{secrets.ACR_NAME}}/${{vars.IMAGE_NAME}} .

      - name: Push Docker image to ACR
        run: |
          docker push ${{secrets.ACR_NAME}}/${{vars.IMAGE_NAME}}

      - name: Deploy to Azure Container Instances
        run: |
          set -euo pipefail
          echo "MODEL_NAME=${{ vars.MODEL_NAME }}"
          echo "IMAGE_NAME=${{ vars.IMAGE_NAME }}"
          echo "ACR_NAME=${{ secrets.ACR_NAME }}"
          echo "RESOURCE_GROUP=${{ secrets.AZURE_RESOURCE_GROUP }}"
          echo "REGION=${{ secrets.AZURE_REGION }}"

          az container create \
          --name ${{vars.MODEL_NAME}} \
          --image ${{secrets.ACR_NAME}}/${{vars.IMAGE_NAME}}:latest \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --registry-login-server ${{secrets.ACR_NAME}} \
          --registry-username ${{ secrets.ACR_USERNAME }} \
          --registry-password ${{ secrets.ACR_PASSWORD }} \
          --environment-variables MODEL_URI="models:/${{ vars.MODEL_NAME }}@${{ secrets.MODEL_ALIAS }}" MLFLOW_TRACKING_URI=${{ vars.MODEL_NAME }} AZURE_STORAGE_CONNECTION_STRING=${{ secrets.AZURE_STORAGE_CONNECTION_STRING }} \
          --dns-name-label ${{ secrets.IMAGE_NAME }}-${{ github.run_id }} \
          --ports 8080 \
          --os-type Linux \
          --cpu 0.5 \
          --memory 1.0 \
          --location ${{ secrets.AZURE_REGION }}

      - name: Wait for container to start
        run: sleep 30

      - name: Probe REST API
        run: |
          curl --fail http://${{ secrets.IMAGE_NAME }}-${{ github.run_id }}.${{ secrets.AZURE_REGION }}.azurecontainer.io:8080/health
